learn_shop:
    resource: "@LearnShopBundle/Resources/config/routing.yml"
    prefix:   /

learn_blog:
    resource: "@LearnBlogBundle/Resources/config/routing.yml"
    prefix:   /

learn_project:
    resource: "@LearnProjectBundle/Resources/config/routing.yml"
    prefix:   /

learn_fos_user:
    resource: "@LearnUserBundle/Resources/config/routing/all.yml"