# app/config/security.yml
imports:
    -   { resource: "@LearnUserBundle/Resources/config/security.yml" }
    
security:
    
    role_hierarchy:
        ROLE_MODERATEUR:    ROLE_USER
        ROLE_SUPER_ADMIN:
            - ROLE_MODERATEUR
            - ROLE_USER
            - ROLE_ALLOWED_TO_SWITCH


    access_control:
        - { path: ^/connexion, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/blog/ajouter-article, role: [ROLE_SUPER_ADMIN, ROLE_MODERATEUR] }
        - { path: ^/blog/modifier-produit/*, role: [ROLE_SUPER_ADMIN, ROLE_MODERATEUR] }
        - { path: ^/blog/supprimer-produit/*, role: [ROLE_SUPER_ADMIN, ROLE_MODERATEUR] }
        - { path: ^/moderation/*, role: [ROLE_SUPER_ADMIN, ROLE_MODERATEUR] }
        - { path: ^/administration/*, role: ROLE_SUPER_ADMIN }