learn_project_blog:
    path:   /blog
    defaults: {_controller: LearnBlogBundle:Blog:Accueil}

learn_project_add_article:
    path:     /blog/ajouter-article
    defaults: { _controller: LearnBlogBundle:Article:Add}

learn_project_modif_article:
    path:     /blog/modifier-produit/{id}
    defaults: { _controller: LearnBlogBundle:Article:Modif}
    options:
        expose: true
    requirements:
        _methods: POST
    
learn_project_suppr_article:
    path:     /blog/supprimer-produit/{id}
    defaults: { _controller: LearnBlogBundle:Article:Suppr}
    options:
        expose: true

learn_project_detail_article:
    path:     /blog/article/{id}
    defaults: { _controller: LearnBlogBundle:Article:Detail}
    requirements:
        id: \d+
        _methods: POST

learn_project_add_comment:
    path:   /comment/{id}
    defaults: { _controller: LearnBlogBundle:Comment:add}
    requirements:
        _method: POST
        id: \d+