learn_project_homepage:
    path:     /
    defaults: { _controller: LearnProjectBundle:Accueil:Accueil}
    
learn_project_contact:
    path:   /contact
    defaults:   {_controller: LearnProjectBundle:User:Contact}