learn_project_homepage:
    path:     /
    defaults: { _controller: LearnProjectBundle:Accueil:Accueil}
    
learn_project_contact:
    path:   /contact
    defaults:   {_controller: LearnProjectBundle:User:Contact}
    
Learn_project_moderation:
    path:   /moderation
    defaults:   {_controller: LearnProjectBundle:Accueil:Moderation}
    
Learn_project_administration:
    path:   /administration
    defaults:   {_controller: LearnProjectBundle:Accueil:Administration}