<?php

namespace Learn\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    
    public function findRecentArticle(){
        
        $query = $this->createQueryBuilder('a')
                ->orderBy('a.datePublication', 'DESC')
                ->setMaxResults(3)
                ->getQuery();
        
        try{
            return $query->getResult();
        } catch (NoResultException $ex) {
            return $ex;
        }
    }
    
}
