<?php

namespace Learn\BlogBundle\Entity;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllCommentById($id)
    {
        $query = $this->createQueryBuilder('c')
                ->where('c.article = :id')
                ->orderBy('c.date', 'DESC')
                ->setParameter(':id', $id)
                ->getQuery();
        
        try{
            return $query->getResult();
        } catch (NoResultException $ex) {
            return $ex;
        }
    }
}
